# Generated by Django 3.0.8 on 2020-08-09 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('commentId', models.AutoField(primary_key=True, serialize=False)),
                ('commentText', models.CharField(max_length=255)),
                ('commentUser', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('imagePath', models.URLField(blank=True)),
                ('category', models.CharField(max_length=255)),
                ('recId', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CommentsReply',
            fields=[
                ('replyText', models.CharField(max_length=255)),
                ('replyId', models.AutoField(primary_key=True, serialize=False)),
                ('replyUser', models.CharField(max_length=10)),
                ('commentReply', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='blogapi.Comments')),
            ],
        ),
        migrations.AddField(
            model_name='comments',
            name='comments',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='blogapi.Posts'),
        ),
    ]
