# Generated by Django 3.0.7 on 2020-06-07 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='posts',
        ),
        migrations.RemoveField(
            model_name='commentsreply',
            name='commentReply',
        ),
        migrations.AddField(
            model_name='comments',
            name='commentsReply',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='blogapi.CommentsReply'),
        ),
        migrations.AddField(
            model_name='posts',
            name='comments',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='blogapi.Comments'),
        ),
    ]
