# Generated by Django 3.0.8 on 2020-09-05 14:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('commentid', models.AutoField(db_column='commentId', primary_key=True, serialize=False)),
                ('commenttext', models.CharField(db_column='commentText', max_length=255)),
                ('commentuser', models.CharField(db_column='commentUser', max_length=255)),
                ('comment_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'comments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CommentsReply',
            fields=[
                ('replyid', models.AutoField(db_column='replyId', primary_key=True, serialize=False)),
                ('replytext', models.CharField(db_column='replyText', max_length=255)),
                ('replyuser', models.CharField(db_column='replyUser', max_length=255)),
                ('reply_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'commentsreply',
                'managed': False,
            },
        ),
    ]
