# Generated by Django 3.0.7 on 2020-06-07 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapi', '0002_auto_20200607_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='commentId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='commentsreply',
            name='replyId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='posts',
            name='recId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
