# Generated by Django 3.0.8 on 2020-08-14 06:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogapi', '0002_auto_20200813_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostAuthorizer',
            fields=[
                ('authorizer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('authorization_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='posts',
            name='activation_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='posts',
            name='is_activated',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posts',
            name='authorizer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blogapi.PostAuthorizer'),
        ),
    ]
