# Generated by Django 3.0.8 on 2020-08-15 05:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogapi', '0005_auto_20200814_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='activation_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
