# Generated by Django 3.0.8 on 2020-08-15 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapi', '0006_auto_20200815_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='activation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
