# Generated by Django 3.0.8 on 2020-08-15 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapi', '0007_auto_20200815_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postauthorizer',
            name='post_id',
        ),
        migrations.AddField(
            model_name='posts',
            name='authorizer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blogapi.PostAuthorizer'),
        ),
    ]
