# Generated by Django 3.0.8 on 2020-08-15 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapi', '0010_auto_20200815_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='postauthorizer',
            name='authorization_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN REVIEW', 'In Review'), ('COMPLETE', 'Complete')], default='PENDING', max_length=15),
        ),
        migrations.AlterField(
            model_name='posts',
            name='category',
            field=models.CharField(choices=[('TECHNOLOGY', 'Technology'), ('AUTOMOBILES', 'Automobiles'), ('ANIMATIONS', 'Animations'), ('DEFAULT', 'Unknown')], default='DEFAULT', max_length=25),
        ),
    ]
