# Generated by Django 3.0.8 on 2020-08-16 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapi', '0012_auto_20200815_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='commentUser',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='commentsreply',
            name='replyUser',
            field=models.CharField(max_length=20),
        ),
    ]
