# Generated by Django 3.0.8 on 2020-08-16 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapi', '0013_auto_20200816_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postauthorizer',
            name='authorization_status',
        ),
        migrations.AddField(
            model_name='postauthorizer',
            name='is_active',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='posts',
            name='authorization_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN REVIEW', 'In Review'), ('COMPLETE', 'Complete')], default='PENDING', max_length=15),
        ),
    ]
